<?php
$recruit=$this->recruit->current();
$form=$this->form;
$follows=$this->follows;
/*有关表格
 * $form (具体见下面代码）
 * 
 * 有关于正文信息
 * $recruit->getRecruitID(); 帖子ID
$recruit->getSchID()//该文作者的学校ID
$recruit->getRtitle();//标题
$recruit->getRtime()//发帖时间 未实现
$recruit->getRcontent()//具体内容
$recruit->getLasttime()//最后一次回复时间（未实现）
$recruit->getRclicknum()//帖子点击量（未实现
$recruit->getRreplynum()//回复量（未实现

$recruit->getUser()->getUserID()
$recruit->getUser()->getUsername()//发文者的name
$recruit->getUser()->getFaceimgpath()//头像地址
foreach ($follows as $follow)
$follow->getUser()->getFaceimgpath()//回复者的头像地址
$follow->getUser()->getUserID()
$follow->getUser()->getUsername()
$follow->getRFollowID()回复的ID
$follow->getRFcontent()回复内容
$follow->getRFtime()回复时间（未实现
 */

echo $this->headtitle($recruit->getRtitle(). "| ContestWeb ");
echo $this->headLink()
->prependStylesheet($this->basePath() . '/css/zq.css');
?>


<div class="row row-offcavnas row-offcanvas-right">
<div class="col-xs-12 col-sm-9">
<div class="row">
       
 <div class="jumpbotron"> <!-- 背景灰-->


    <h2  id="font-title"> <?=$recruit->getRtitle()?></h1><br>
    <div id="font-sourcetxt" ><hr> <?=$recruit->getRcontent();?></div>
    <span id="fontsmall" >发表者： <?=$recruit->getUser()->getUsername();?></span> 
 </div>
</div>

    <h2>评论</h2>
    
        <?php foreach ($follows as $follow):?>
    <div class="row">
    	<div class="col-12 col-sm-6 col-lg-12 zq01">
  
        <h5 id="font-regular">评论者:<?= $follow->getUser()->getUsername();?></h5>
        <img class="img-circle" id="touxiang" src="<?= $follow->getUser()->getFaceimgpath();?>"/>
       <span id="fontadd"><?= $follow->getRFcontent();?></span><hr>    
      </div>
      </div>  
    <?php endforeach;?>
    
    
  
    <div class="row row-offcavnas row-offcanvas-right">
<div class="col-xs-12 col-sm-9">
<div class="row">
    <h4 id="font-regular">发表评论</h4>
     <?php 
    $form->setAttribute('action', '/recruit/'.$recruit->getRecruitID());//注意这里写绝对路径
    $form->prepare();
    echo $this->form()->opentag($form);//<form>
       echo $this->formRow($form->get('rfcontent')).'<br>';
       echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();//</form>
?>
    
</div></div></div>