
 <?php echo $this->headLink()
->prependStylesheet($this->basePath() . '/css/ptt.css');

/*可以调用的方法*/
/*
 * 推荐
 * 
 * 
 *  $recruit->getRecruitID(); 帖子ID
    $recruit->getRtitle(); 标题
    $recruit->getRtime(); //未完成
    $recruit->getRcontent(); 内容
    $recruit->getLasttime();//最后回复时间 未完成
    $recruit->getRclicknum(); 点击量 未完成
    $recruit->getRreplynum(); 回复量 未完成
    $recruit->getTag(); 标签
    $recruit->getUser()->getUsername();作者名称
    $recruit->getUser()->getFaceimgpath();作者头像
    
    
 */

 echo $this->headtitle("招募 | ContestWeb ");
if($this->islogin == false)
    echo "<a href='/login'>登录</a>之后才可以查看本校的招募。";

?>
    <div class="row">
   
                

  <div class="col-md-12">

 
 <div class="btn-group" role="group" aria-label="recruittype">
              <button type="button" onclick="window.location.href='/recruit?type=1'" class="btn btn-default <?=$this->type==1?"active":" "; ?>">人才招募</button>
              <button type="button" onclick="window.location.href='/recruit?type=2'" class="btn btn-default <?=$this->type==2?"active":" "; ?>">团队招募</button>
        </div>
        <br><br>
      <script type="text/javascript">
      var myRul=document.getElementById("rul");
      var myRli=myRul.getElementsByTagName("li");
      function changeColor(x){
  	     for(var i=0;i<myRli.length;i++){
  	  	     myRli[i].className="";
          };
          x.className="active";
      }
      </script>
        <div class="row">
            <div class="col-md-12">
        <?php 

    $recruits=$this->recruits;
    if($this->type == 1):
    foreach ($recruits as $recruit):?>
        <!--个人-->
          <div class="col-sm-6 col-md-3">
          
            <div class="thumbnail">
              <img src="<?=$recruit->getUser()->getFaceimgpath(); ?>" alt="..." class="img-circle headimg">
              <div class="caption">
                <h3 class="text-center"><?=$recruit->getUser()->getUserName(); ?></h3>
                <p class="text-center"><?=$recruit->getRtitle() ?></p>
                <?php 
                $tagar = explode(',',$recruit->getTag());
                    foreach ($tagar as $t):
                ?>
                <span class="label label-primary"><?=$t;?></span>
                <?php 
                    endforeach;
                /*
                 *                 <span class="label label-primary"><?=$recruit->getTag();?></span>
                <span class="label label-success"><?=$recruit->getTag();?></span>
                <span class="label label-info"><?=$recruit->getTag();?></span>
                <span class="label label-warning"><?=$recruit->getTag();?></span>
                <span class="label label-danger"><?=$recruit->getTag();?></span>
                <span class="label label-danger"><?=$recruit->getTag();?></span>
                 */?>
                <br><br>
                <p class="text-center"><a href="/recruit/<?=$recruit->getRecruitID() ?>" class="btn btn-primary" role="button" >详细信息</a> <a href="/account/<?=$recruit->getUser()->getUserID() ?>" class="btn btn-default" role="button">个人主页</a></p>
              </div>
            </div>
        </div>
          <?php endforeach;
          else:
          foreach ($recruits as $recruit):
          ?>
           <!--团队-->
           <div class="col-sm-6 col-md-3">
          
            <div class="thumbnail">
             
              <div class="caption">

               
               <div class="row">
               		<div class="col-md-4"><img src="<?=$recruit->getUser()->getFaceimgpath(); ?>" alt="..." class="img-rounded teamimg"></div>
                    <div class="col-md-8"><h4 >团队名称</h4></div>  
                    <div class="col-md-8 text-center"><h6 >发起人：<?=$recruit->getUser()->getUserName(); ?></h6></div>          
               </div>
                
                <p class="text-center"> <?=$recruit->getRcontent();?></p>
                
                <p class="text-center"><a href="/recruit/<?=$recruit->getRecruitID() ?>" class="btn btn-primary" role="button">团队详情</a> <a href="/account/<?=$recruit->getUser()->getUserID() ?>" class="btn btn-default" role="button">与Ta联系</a></p>
              </div>
            </div>
          </div>
          <?php endforeach;
          endif;
          ?>
          <?php 
    if($this->islogin === true&&$this->type == 1):

?><br><br>
    <h3>您可能对这些用户招募感兴趣:</h3>

    <?php foreach ($this->recs as $r):?> 
     <div class="col-sm-6 col-md-3">
          
            <div class="thumbnail">
              <img src="<?=$r->getUser()->getFaceimgpath(); ?>"  class="img-circle headimg">
              <div class="caption">
                <h3 class="text-center"><?=$r->getUser()->getUserName(); ?></h3>
                <p class="text-center"><a href = "/recruit/<?=$r->getRecruitID(); ?>"><?= $r->getRtitle()?></a></p>

                <p class="text-center"><a href="/recruit/<?=$r->getRecruitID() ?>" class="btn btn-primary" role="button" >详细信息</a> <a href="/account/<?=$r->getUser()->getUserID() ?>" class="btn btn-default" role="button">个人主页</a></p>
              </div>
            </div>

        </div>
        <?php endforeach;endif;?>
          </div>
        </div>
        <?php /*
        <nav>
          <ul class="pagination">
            <li>
              <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li  class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
              <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>*/?>
<!--         推荐 -->

    
<?php     
    //最后添加js
    echo $this->inlineScript()->prependFile($this->basepath('/js/pttmain.js'));
?>