 <?php echo $this->headLink()
->prependStylesheet($this->basePath() . '/css/ptt.css');
/*可以调用的方法*/
/*
 *  $recruit->getRecruitID(); 帖子ID
    $recruit->getRtitle(); 标题
    $recruit->getRtime(); //未完成
    $recruit->getRcontent(); 内容
    $recruit->getLasttime();//最后回复时间 未完成
    $recruit->getRclicknum(); 点击量 未完成
    $recruit->getRreplynum(); 回复量 未完成
    $recruit->getTag(); 标签
    $recruit->getUser()->getUsername();作者名称
    $recruit->getUser()->getFaceimgpath();作者头像
 */

echo $this->headtitle("招募 | ContestWeb ");

 
 <div class="btn-group" role="group" aria-label="recruittype">
              <button type="button" class="btn btn-default active">人才招募</button>
              <button type="button" class="btn btn-default">团队招募</button>
        </div>
        <br><br>
        

        <ul class="nav nav-pills">
          <li role="presentation" class="active"><a href="#">全部</a></li>
          <li role="presentation"><a href="#">计算机</a></li>
          <li role="presentation"><a href="#">科研立项</a></li>
          <li role="presentation"><a href="#">后台</a></li>
          <li role="presentation"><a href="#">美工</a></li>
          <li role="presentation"><a href="#">挑战杯</a></li>
          <li role="presentation"><a href="#">挑战杯</a></li>
          <li role="presentation"><a href="#">挑战杯</a></li>
          <li role="presentation"><a href="#">挑战杯</a></li>
          <li role="presentation"><a href="#">挑战杯</a></li>
          <li role="presentation"><a href="#">挑战杯</a></li>
        </ul>
        <br>
        <div class="row">
        <?php 

    $recruits=$this->recruits;

    foreach ($recruits as $recruit):?>
        <!--个人-->
          <div class="col-sm-6 col-md-3">
          
            <div class="thumbnail">
              <img src="<?=$recruit->getUser()->getFaceimgpath(); ?>" alt="..." class="img-circle headimg">
              <div class="caption">
                <h3 class="text-center"><?=$recruit->getUser()->getUserName(); ?></h3>
                <p class="text-center">女</p>
                <span class="label label-default"><?=$recruit->getTag();?></span>
                <span class="label label-primary"><?=$recruit->getTag();?></span>
                <span class="label label-success"><?=$recruit->getTag();?></span>
                <span class="label label-info"><?=$recruit->getTag();?></span>
                <span class="label label-warning"><?=$recruit->getTag();?></span>
                <span class="label label-danger"><?=$recruit->getTag();?></span>
                <span class="label label-danger"><?=$recruit->getTag();?></span>
                <br><br>
                <p class="text-center"><a href="#" class="btn btn-primary" role="button">Ta的简历</a> <a href="#" class="btn btn-default" role="button">个人主页</a></p>
              </div>
            </div>
          </div>
          
           <!--团队-->
           <div class="col-sm-6 col-md-3">
          
            <div class="thumbnail">
             
              <div class="caption">
               
               <div class="row">
               		<div class="col-md-4"><img src="<?=$recruit->getUser()->getFaceimgpath(); ?>" alt="..." class="img-rounded teamimg"></div>
                    <div class="col-md-8"><h4 >团队名称</h4></div>  
                    <div class="col-md-8 text-center"><h6 >发起人：<?=$recruit->getUser()->getUserName(); ?></h6></div>          
               </div>
                
                <p class="text-center"> <?=$recruit->getRcontent();?></p>
                
                <p class="text-center"><a href="#" class="btn btn-primary" role="button">团队详情</a> <a href="#" class="btn btn-default" role="button">与Ta联系</a></p>
              </div>
            </div>
          </div>
          <?php endforeach;?>
        </div>
        
        <nav>
          <ul class="pagination">
            <li>
              <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li  class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
              <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
        
<?php     
    //最后添加js
    echo $this->inlineScript()->prependFile($this->basepath('/js/pttmain.js'));
?>