<div class="navbar navbar-fixed-top navbar-inverse" role="navigation"id = "userPanel">
	<div class="container-fluid">
    	<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            	<span class="sr-only">菜单</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>   
            <a class="navbar-brand" href="#"> 科研平台LOGO</a>     
        </div>
        <div class="navbar-collapse collapse">
			<ul class="nav navbar-nav"> 
            	<li class="active"><a href="#">首页</a></li>
                <li class="active"><a href="source.html">科研资源</a></li>
                <li class="active"><a href="#">人才招募</a></li>
                <li class="active"><a href="#">关于我们</a></li>
            </ul>       
           <ul class="nav navbar-nav navbar-right"> 
           	 <li class="dropdown">
           	  <?php 
            	if ($this->identity){?>
            		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
            		<?php echo $this->identity?>
            		<b class="caret"></b>
            		</a>
            		<ul class="dropdown-menu">
            		<li><a href="/account/<?=$this->userID ?>">个人主页</a></li>
            		<li><a href="#">私信</a></li>
            		<li><a href="#">设置</a></li>
            		<li><a href="<?php $this->currentPage ?>?logout=1">注销</a></li>
            		</ul>
            	<?php }
            	else{?>
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
            	登陆\注册
            	<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
            		<li><a href="/login">登陆</a></li>
            		<li><a href="/register">注册</a></li>
                </ul>
            	<?php 
            		}
            	?>
   
             </li>
           </ul>


        </div>
    </div>
</div>
<br><br><br>