<?php
$page=$this->page->current();
$form=$this->form;
$follows=$this->follows;
/*有关表格
 * $form (具体见下面代码）
 * 
 * 有关于正文信息
 * $page->getPageID();
$page->getSchID()//该文作者的学校ID
$page->getFilepath()//上传文件的地址
$page->getSecID()//对应科研立项、挑战杯……的ID
$page->getPtitle();//标题
$page->getPtime()//发帖时间
$page->getPcontent()//具体内容
$page->getLasttime()//最后一次回复时间（未实现）
$page->getPtype()//ID对应全部、本届信息、往届信息……
$page->getPclicknum()//帖子点击量（未实现
$page->getPreplynum()//回复量（未实现
$page->getPzannum()//点赞数（未实现
$page->getPallow()//本帖是否允许外校查看，1代表是，0代表否

$page->getUser()->getUserID()
$page->getUser()->getUsername()//发文者的name

$page->getPcontent();  //具体内容
 */
?>


    <h1>标题： <?=$page->getPtitle()?></h1><br>
    <p>正文信息 <?=$page->getPcontent();?></p>
    <p>发表者用户名 <?=$page->getUser()->getUsername();?></p>
    <h2>评论</h2>
    <?php foreach ($follows as $follow):?>
        <p>评论者用户名:<?= $follow->getUser()->getUsername();?></p>
        <p>评论内容:<?= $follow->getFcontent();?></p>
    <?php endforeach;?>
    <h2>发表评论</h2>
    <?php 
    $form->setAttribute('action', '/page/'.$page->getPageID());//注意这里写绝对路径
    $form->prepare();
    echo $this->form()->opentag($form);//<form>
       echo $this->formRow($form->get('fcontent')).'<br>';
       echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();//</form>
?>