<?php
$page=$this->page->current();
$form=$this->form;
$follows=$this->follows;
/*有关表格
 * $form (具体见下面代码）
 * 
 * 有关于正文信息
 * $page->getPageID();
$page->getSchID()//该文作者的学校ID
$page->getFilepath()//上传文件的地址
$page->getSecID()//对应科研立项、挑战杯……的ID
$page->getPtitle();//标题
$page->getPtime()//发帖时间
$page->getPcontent()//具体内容
$page->getLasttime()//最后一次回复时间（未实现）
$page->getPtype()//ID对应全部、本届信息、往届信息……
$page->getPclicknum()//帖子点击量（未实现
$page->getPreplynum()//回复量（未实现
$page->getPzannum()//点赞数（未实现
$page->getPallow()//本帖是否允许外校查看，1代表是，0代表否

$page->getUser()->getUserID()
$page->getUser()->getUsername()//发文者的name
$page->getUser()->getFaceimgpath()//头像地址
$page->getPcontent();  //具体内容
foreach ($follows as $follow)
$follow->getUser()->getFaceimgpath()//回复者的头像地址
$follow->getUser()->getUserID()
$follow->getUser()->getUsername()
$follow->getFollowID()回复的ID
$follow->getFcontent()回复内容
$follow->getFtime()回复时间（未实现
 */
?>
<style type="text/css">
/* 灰色背景星星5个平铺 */
.star_bg {
    width: 120px; height: 20px;
    background: url(/img/grey.jpg) repeat-x;
    position: relative;
    overflow: hidden;
}
/* 这是5个小星星们的默认状态的定位 */
.star {
    height: 100%; width: 24px;
    line-height: 6em;
    position: absolute;
    z-index: 3;
}
.star_1 { left: 0; }
.star_2 { left: 24px; }
.star_3 { left: 48px; }
.star_4 { left: 72px; }
.star_5 { left: 96px; }

/* 鼠标hover效果实现，分别显示背景与定宽 */
.star:hover {    
    background: url(/img/yellow.jpg) repeat-x ;
    left: 0; z-index: 2;
}
.star_1:hover { width: 24px; }
.star_2:hover { width: 48px; }
.star_3:hover { width: 72px; }
.star_4:hover { width: 96px; }
.star_5:hover { width: 120px; }
</style>




    <h1>标题： <?=$page->getPtitle()?></h1><br>
    <p>正文信息 <?=$page->getPcontent();?></p>
    <p>发表者用户名 <?=$page->getUser()->getUsername();?></p>
    <a href="<?=$page->getFilepath() ?>">下载附件(或者右键另存为)</a>
    <h2>评分：</h2>
    <p>请对本资源或内容进行评分</p>
    
    <div class="star_bg">
        <a class="star star_1"></a>
        <a class="star star_2"></a>
        <a class="star star_3"></a>
        <a class="star star_4"></a>
        <a class="star star_5"></a>
    </div>
    
    <h2>评论</h2>
    <?php foreach ($follows as $follow):?>
    
        <p>评论者用户名:<?= $follow->getUser()->getUsername();?></p>
        <p>评论者头像:<img src="<?= $follow->getUser()->getFaceimgpath();?>"/></p>
        <p>评论内容:<?= $follow->getFcontent();?></p>
    <?php endforeach;?>
    <h2>发表评论</h2>
    <?php 
    $form->setAttribute('action', '/page/'.$page->getPageID());//注意这里写绝对路径
    $form->prepare();
    echo $this->form()->opentag($form);//<form>
       echo $this->formRow($form->get('fcontent')).'<br>';
       echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();//</form>
?>
<h2>和本文类似的文章：</h2>
