<?php echo $this->headLink()
->prependStylesheet($this->basePath() . '/css/zq.css');
      echo $this->headtitle("关于我们 | ContestWeb");
?>
<div class="row">
<div class="contact1">
        
            <div class="contact-top">
                <img src="/img/logo.png" style="width:200px;width:200px;" alt="" />
                <hr>
                <p id="font-title" style="color:#0e90d2">山东大学（威海）科研平台</p><hr>
                 <h4 id="font-sourcetxt">欢迎关注SDU科研平台，分享资源、经验、通知等，我们根据个人兴趣推荐适合你的文章。</h4>
            </div>
            <div class="contact-bottom">
            <h4 id="font-sourcetxt">用户反馈</h4><hr>
                <input type="text" value="姓名" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = '姓名';}"/>
                <input type="text" value="联系方式" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = '联系方式';}"/>
                <textarea value="反馈建议" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = '反馈建议';}">反馈建议
                </textarea>
                <div class="contact-but">
                            <input type="submit" value="发送信息" />
                        </div>
            </div>
        </div>
    </div>







