<?php echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/zq.css')?>



<?php
/*
 * 
 */

//改变config要清楚浏览器缓存
echo $this->headmeta('utf-8');
   echo $this->headScript()
        ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
        ->prependFile($this->basePath() . '/ckeditor/config.js'); //这一行 
   
   $form = $this->pageform;
   $form->setAttribute('action', $this->url());
   $form->prepare();
//    echo $this->form($form);
   echo $this->form()->opentag($form);//<form>
   ?>
   
 <!-- <script>
 var parentValue=""; 
var el = document.getElementById('slt');
parentValue=select.options[select.selectedIndex]; 

parentValue.className += 'dropdown-menu';

</script> -->
 
   
     <label id="fontadd">
比赛项目：
</label>  


   <?php 
   echo $this->formRow($form->get('secID')).'<br>';?>
   
    <label id="fontadd">
发帖种类：
</label> 

   <?php 
   echo $this->formRow($form->get('ptype')).'<br>';
   ?>
<label id="fontadd">
标题：
</label>
   
   <?php 
   echo $this->formRow($form->get('ptitle'));?>

   <?php
   echo $this->formRow($form->get('pcontent'));?>
   <label id="font-addsmall">
是否允许其他学校查看本文?
</label>
 <?php 
   echo $this->formRow($form->get('pallow'));
   ?>
   <br>
   
      <label id="fontadd">
附加文件
</label>
   <?php 
   echo $this->formRow($form->get('filepath')).'<br>';
   ?>
   <?php 
   echo $this->formSubmit($form->get('submit'));
   echo $this->form()->closeTag();//</form>
   ?>
               <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
        	//customConfig: '<php $this->basepath()?>/ckeditor/customconfig.js'
            CKEDITOR.replace( 'editor1', {
           	 filebrowserUploadUrl: "/addUpPicSer"
            });
            </script>
   