<?php
/*
 * 
 */

//改变config要清楚浏览器缓存
echo $this->headmeta('utf-8');
   echo $this->headScript()
        ->prependFile($this->basePath() . '/ckeditor/ckeditor.js')
        ->prependFile($this->basePath() . '/ckeditor/config.js'); //这一行 
   
   $form = $this->pageform;
   $form->setAttribute('action', $this->url());
   $form->prepare();
//    echo $this->form($form);
   echo $this->form()->opentag($form);//<form>
   ?>
   <?php 
   echo $this->formRow($form->get('secID')).'<br>';?>
   <?php 
   echo $this->formRow($form->get('ptype')).'<br>';
   echo $this->formRow($form->get('ptitle'));
   echo $this->formRow($form->get('pcontent'));
   echo $this->formRow($form->get('pallow'));
   echo $this->formRow($form->get('filepath')).'<br>';
   echo $this->formSubmit($form->get('submit'));
   echo $this->form()->closeTag();//</form>
   ?>
               <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
        	//customConfig: '<php $this->basepath()?>/ckeditor/customconfig.js'
            CKEDITOR.replace( 'editor1', {
           	 filebrowserUploadUrl: "/addUpPicSer"
            });
            </script>
   