<?php
$page=$this->page->current();
/*
 * $page->getPageID();
$page->getSchID()//该文作者的学校ID
$page->getFilepath()//上传文件的地址
$page->getSecID()//对应科研立项、挑战杯……的ID
$page->getPtitle();//标题
$page->getPtime()//发帖时间
$page->getPcontent()//具体内容
$page->getLasttime()//最后一次回复时间（未实现）
$page->getPtype()//ID对应全部、本届信息、往届信息……
$page->getPclicknum()//帖子点击量（未实现
$page->getPreplynum()//回复量（未实现
$page->getPzannum()//点赞数（未实现
$page->getPallow()//本帖是否允许外校查看，1代表是，0代表否

$page->getUser()->getUserID()
$page->getUser()->getUsername()//发文者的name

$page->getPcontent();  //具体内容
 */
?>
<?php 

    echo '<h1>'.$page->getPtitle().'</h1><br>';
    echo $page->getPcontent();
    echo $page->getUser()->getUsername();
?>