<?php
/*本页返回数据
 * 更新以下可用
 * 推荐
 * foreach($this->recs as $rec)
 * 
 * $page->getPclicknum()//帖子点击量
$page->getPreplynum()//回复量
$page->getPzannum()//点赞数
$page->getPtime()//发帖时间

$this->pages  //所有的page 类
foreach($this->pages as $page)
    在里面可以引用$page->get***
endforeach
$page->getPageID();
$page->getSchID()//该文作者的学校ID
$page->getFilepath()//上传文件的地址
$page->getSecID()//对应科研立项、挑战杯……的ID
$page->getPtitle();//标题

$page->getPcontent()//具体内容
$page->getLasttime()//最后一次回复时间（未实现）
$page->getPtype()//ID对应全部、本届信息、往届信息……

$page->getPallow()//本帖是否允许外校查看，1代表是，0代表否

$page->getUser()->getUserID()
$page->getUser()->getUsername()//发文者的name
$page->getUser()->getFaceimgpath()//头像地址

$page->getPcontent();  //具体内容
$
*/
?>
<?php 
echo $this->headLink()
->prependStylesheet($this->basePath() . '/css/source.css');
?>
<?php echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/zq.css')?>
<?php


     echo $this->inlineScript()->prependFile($this->basePath('js/jump.js'));

?>

<script type="text/javascript">
var body=document.getElementsByTagName("body"); 
body[0].setAttribute("onload","init(<?php echo $this->secID;?>,<?php echo $this->ptype;?>)");
</script>


<div class="row"> 
    <div class="col-md-2 lead">
     <strong>全部资源</strong>
    </div> 
   </div> 
   <div class="row"> 
    <div class="col-md-12"> 
     <div class="well"> 
      <!-- filterable portfolio menu starts --> 
      <ul class="portfolioMenuWrapper " id="portfolioMenuWrapper"> 
       <li><a id="0" onclick="jump(this.id);return false;" href="" data-type="all" class="currentPortfolioFilter">全部</a></li> 
       <li><a id="1"  onclick="jump(this.id);return false;" href="" data-type="科研立项">科研立项</a></li> 
       <li><a id="2" onclick="jump(this.id);return false;" href="" data-type="齐鲁软件">齐鲁软件</a></li> 
       <li><a id="3" onclick="jump(this.id);return false;" href="" data-type="挑战杯">挑战杯</a></li> 
      </ul>
      <br /> 
      <ul class="portfolioMenuWrapper " id="portfolioMenuWrapper2"> 
       <li><a id="t0" onclick="jump2(this.id);return false;" href="" data-type="all" class="currentPortfolioFilter">全部</a></li> 
       <li><a id="t1" onclick="jump2(this.id);return false;" href="" >本届信息</a></li> 
       <li><a id="t2" onclick="jump2(this.id);return false;" href="" >往届信息</a></li> 
       <li><a id="t3" onclick="jump2(this.id);return false;" href="" >经验交流</a></li> 
       <li><a id="t4" onclick="jump2(this.id);return false;" href="" >资源分享</a></li> 
      </ul>
      
      
      
      
      
      <script >
//       $('#portfolioMenuWrapper > li > a').click(function(){
//     		$('.currentPortfolioFilter').removeClass('currentPortfolioFilter');
//     		this.addClass('currentPortfolioFilter');
//     })
/* filterable portfolio functions start
	$('#portfolioMenuWrapper > li > a').click(function(){
		var filterVal = $(this).attr('data-type');
		if(filterVal != 'all'){
			$('.currentPortfolioFilter').removeClass('currentPortfolioFilter');
			$(this).addClass('currentPortfolioFilter');
			$('.portfolioFilterableItemWrapper').each(function(){
				var itemCategories = $(this).attr("data-type").split(",");
				if($.inArray(filterVal, itemCategories) > -1){
					$(this).addClass('filteredPortfolioItem');
   	       			$('.filteredPortfolioItem').stop(true, true).animate({opacity:1}, 300, 'easeOutCubic');
				}else{
					$(this).removeClass('filteredPortfolioItem');
					if(!$(this).hasClass('filteredPortfolioItem')){
						$(this).stop(true, true).animate({opacity:0.3}, 300, 'easeOutCubic');
					};
				};
			});
		}else{
			$('.currentPortfolioFilter').removeClass('currentPortfolioFilter');
			$(this).addClass('currentPortfolioFilter');
			$('.filteredPortfolioItem').removeClass('filteredPortfolioItem');
			$('.portfolioFilterableItemWrapper').stop(true, true).animate({opacity:1}, 300, 'easeOutCubic');
		}
		return false;
	});
	// filterable portfolio functions end*/
	</script>
      <!-- filterable portfolio menu ends --> 
     </div> 
 <form action="/search" method="get" class="input-group">
    <input name="q"type = "text" class="form-control" placeholder="查询内容">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">搜索</button>
      </span>
    <!-- <input name="submitsearch" type="submit" lass="btn btn-default"> -->
</form>
   <div class="recommond" id="fontadd">
    <h4 id="font-recom1">您可能对以下文章感兴趣：</h4>
    <br>
    <?php $hasFlag = false;//是否有推荐内容?>
    <?php if($this->whetherLogIn === false):?>
      
         <p id="font-recom2">请先<a href = "/login">登录</a>获取与您兴趣一致的推荐<p>
         
    <?php elseif ($this->recs !== null):?>

    <?php foreach ($this->recs as $rec):
        $hasFlag=true;?>
  <div class="pagelist">
   <p id="font-regular">标题：
   <a id="font-addsmall" href = <?="/page/".$rec->getPageID(); ?>><?= $rec->getPtitle(); ?></a></p>
      
      <hr>
 </div>

    <?php endforeach;
          endif;?>
    <?php if($hasFlag===false):?>
   <p id="font-recom2"> 请对您浏览的内容进行评分让我们更好得为您推荐</p>
    <?php endif;?>
</div>

  </div> 
   </div>
   
   <hr/> 
<div class="span12">
 <hr>
      
      <p style="font-size:18px;font-weight: bold;color:#0e90d2;font-family:'Montserrat', sans-serif;">资源文章列表</p><hr>
      </div>

<?php 
 foreach ($this->pages as $page): ?>
   <div class="row">
    <div class="col-md-12">
      <ul class="ask-list">
       <li> <a href="page/<?php echo $page->getPageID() ?>"> <h4><?= $page->getPtitle() ?></h4> </a> <p><?= $page->getPcontent() ?> </p> <span class="ask-descrip">2015/10/10 8:00</span> </li>
       </ul>
    </div>
   </div>
   
<?php endforeach ?>

