<?php echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/homepage.css');
        echo $this->headtitle("欢迎 大学生科研平台");
?>
            
            <section id="page-breadcrumb" >
    <div class="vertical-center ">
        <div class="container">
            <div class="row">
                
                    <div class="col-sm-12">
                      <div id="bgimg">
                        <h1>科研互动平台</h1>
                        <p>Research  With  Interaction</p>
                       </div>
                    </div>
                
            </div>
        </div>
    </div>
</section>

<section id="blog" class="padding-top">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                         <div class="col-sm-12 col-md-12">
                            <div class="single-blog single-column">
                                <div class="post-thumb">
                                    <a href="/p/1002"><img src="/img/cccc1.jpg" class="img-responsive" alt=""></a>
                                    <div class="post-overlay">
                                       <span class="uppercase"><a href="#">19 <br><small>Apr</small></a></span>
                                   </div>
                                </div>
                                <div class="post-content overflow">
                                    <h2 class="post-title bold"><a href="p/1002">2016年中国高校计算机大赛--团体程序设计天梯赛报名通知</a></h2>
                                    
                                    <p>中国高校计算机大赛（China  Collegiate  Computing Contest，简称C4）是面向全国高校各专业在校学生的科技类竞赛活动，旨在促进高校计算机课程教学内容和教学方法改革强化学生创新意识，提升学生计算机问题求解水平，特别是计算机程序设计、大数据处理和移动应用的设计与开发能力，增强计算机应用能力，培养团队合作精神，提高大学生的综合素质，促进校际交流，丰富校园学术气氛。</p>
                                    <a href="p/1002" class="read-more">查看详情</a>
                                    <div class="post-bottom overflow">
                                        <ul class="nav navbar-nav post-nav">
                                            <li><a href="#"><i class="fa fa-tag"></i>日期 2016-04-19 </a></li>
                                            <li><a href="#"><i class="fa fa-heart"></i>点击量 88</a></li>
                                            <li><a href="#"><i class="fa fa-comments"></i>评论 3</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-12">
                            <div class="single-blog single-column">
                                <div class="post-thumb">
                                    <a href="/p/1001"><img src="/img/acm1.jpg" class="img-responsive" alt=""></a>
                                    <div class="post-overlay">
                                       <span class="uppercase"><a href="/p/1001">18 <br><small>Apr</small></a></span>
                                   </div>
                                </div>
                                <div class="post-content overflow">
                                    <h2 class="post-title bold"><a href="/p/1001">2016山东大学(威海)第三届大学生程序设计竞赛通知</a></h2>
                                    
                                    <p>为培养我校学生创新能力、团队精神和利用计算机分析问题、解决实际问题的能力，提高全校学生综合素质和计算机编程水平，定于2016年4月23日举行“2016山东大学(威海)第三届大学生程序设计竞赛”。</p>
                                    <a href="/p/1001" class="read-more">查看详情</a>
                                    <div class="post-bottom overflow">
                                        <ul class="nav navbar-nav post-nav">
                                            <li><a href="#"><i class="fa fa-tag"></i>日期 2016-04-18</a></li>
                                            <li><a href="#"><i class="fa fa-heart"></i>点击量 28</a></li>
                                            <li><a href="#"><i class="fa fa-comments"></i>评论 0</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>

                 </div>
                <div class="col-md-3 col-sm-5">
                    <div class="sidebar blog-sidebar">
                        <div class="sidebar-item  recent">
                            <h3>快速通道</h3>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="/add"><img src="/img/project1.jpg" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="/add" style="display:table-cell;height:50px;vertical-align:middle;">上传资源</a></h4>
                                    
                                </div> 
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="/radd"><img src="/img/project2.jpg" alt=""></a>
                                </div>
                                <div class="media-body">
                                    <h4><a href="/radd" style="display:table-cell;height:50px;vertical-align:middle;">团队招募</a></h4>
                                   
                                </div>
                            </div>
                            <div class="media">
                                <div class="pull-left">
                                    <a href="/radd"><img src="/img/project3.jpg" alt=""></a>
                                </div>
                                <div class="media-body" style="">
                                    <h4><a href="/radd" style="display:table-cell;height:50px;vertical-align:middle;">人才自荐</a></h4>
                                    
                                </div>
                            </div>
                        </div>
                        <div class="sidebar-item categories">
                            <h3>大赛信息</h3>
                            <ul class="nav navbar-stacked">
                                <li><a href="/page?secID=1&ptype=0">科研立项<span class="pull-right">(1)</span></a></li>
                                <li><a href="/page?secID=2&ptype=0">齐鲁软件<span class="pull-right">(8)</span></a></li>
                                <li><a href="/page?secID=3&ptype=0">挑战杯<span class="pull-right">(4)</span></a></li>
                                <li><a href="/page?secID=4&ptype=0">ACM竞赛<span class="pull-right">(9)</span></a></li>
                            </ul>
                        </div>                       
                        <div class="sidebar-item popular">
                            <h3>人才信息</h3>
                            <ul class="gallery">
                                <li><a href="/account/4"><img src="/img/user1_1.jpg" alt=""></a></li>
                                <li><a href="/account/5"><img src="/img/user1_2.jpg" alt=""></a></li>
                                <li><a href="/account/6"><img src="/img/user1_3.jpg" alt=""></a></li>
                                <li><a href="/account/8"><img src="/img/user2_1.jpg" alt=""></a></li>
                                <li><a href="/account/9"><img src="/img/user2_2.jpg" alt=""></a></li>
                                <li><a href="/account/10"><img src="/img/user2_3.jpg" alt=""></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>  
 
 
 