<?php 
 $form = $this->userform;
//设置表单的action属性，跳转到album/add 然后addAction()getRequest；和正常的方式是类似的。
$form->setAttribute('action', $this->url());
$form->setAttribute('id','foo');//这里设置你的id
$form->prepare();

echo $this->form()->openTag($form);//<form>
 echo $this->formHidden($form->get('userID'));
 ?>
 <label>
 <span>your username</span>
 <?php 
echo $this->formRow($form->get('username'));
?></label>
<?php 
echo $this->formRow($form->get('upassword'));
 echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();